### ISSUE TITLE
Create an event page for every event where we display it as a card with its details.

### ISSUE THREAD

**Issue by C901EE** [Fagyesz/Carpe-Diem#107]

**Comment by Fagyesz** [comment]
1.   Create a dedicated event page for every event that is linked from the event listings page.
2.    Display the event as a card with its details, including the event name, date, time, location, description, and pricing information.
3.    Add a call-to-action button to the card that allows users to purchase tickets for the event.
4.    Implement a responsive design for the event card that ensures it looks good on different devices and screen sizes.
5.    Allow event organizers to upload pictures for their events to display on the event card.
6.    Include social media share buttons on the event card to allow users to easily share the event with their friends and followers.
