### ISSUE TITLE
Software Functional Specification #2 - Funkcionális követelmények

### ISSUE THREAD

**Issue by Lisense05** [Fagyesz/Carpe-Diem#23]

**Comment by Fagyesz** [comment]
Alapvetően 3 jogosultság létezik. Guest, User, Admin

- Guest felhasználóként, kizárólag az oldalon elérhető eseményeket tudja keresni/böngészni. Az eseményhez tartozó részletes információkat eléri. pl: Időpont, helyszín, ár, elérhető DB szám. Megvásárláshoz már be kell jelentkeznie.

- User felhasználóként már bejelentkezve elérhető a vásárlás a megfelelő adatok megadásával. Adott jegy vásárlás után a User megkapja a részletes információkat, illetve külön fülön láthatja az adott megvásárolt jegyeit. Ezek a jegyek QR kóddal vannak ellátva. A megvásárolt jegyet akár beillesztheti a User a saját google calendarjába.

- Admin felhasználóként bejelentkezve elérhetjük az admin felületet, ahol létre lehet hozni eventeket illetve módosítani, törölni. Az eventeken belül kezelni a jegyeket külön is akár. Alapvető statisztikákat látni az adott eventtel kapcsolatosan.

by lisnse05
